//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPurchaseSystem.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> AirplaneId { get; set; }
        public Nullable<int> ScheludeId { get; set; }
        public Nullable<int> FlyTypeId { get; set; }
    
        public virtual Airplanes Airplanes { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual FlyTypes FlyTypes { get; set; }
        public virtual Schedules Schedules { get; set; }
    }
}
